//! Crypttab generation for LUKS containers

use crate::config::DeploymentConfig;
use crate::configure::encryption::get_luks_uuid;
use crate::disk::detection::partition_path;
use crate::utils::command::CommandRunner;
use crate::utils::error::Result;
use std::fs;
use tracing::info;

/// Generate /etc/crypttab for the installed system
pub fn generate_crypttab(
    cmd: &CommandRunner,
    config: &DeploymentConfig,
    device: &str,
    luks_partition: u32,
    install_root: &str,
) -> Result<()> {
    info!("Generating /etc/crypttab");

    let luks_device = partition_path(device, luks_partition);

    // Extract the mapping name without "Crypt-" prefix for crypttab
    // crypttab uses the base name (e.g., "Root"), the hook adds "Crypt-" prefix
    let mapper_name = config
        .disk
        .luks_mapper_name
        .trim_start_matches("Crypt-")
        .to_string();

    if cmd.is_dry_run() {
        println!("  [dry-run] Would generate /etc/crypttab:");
        println!("    {} UUID=<LUKS_UUID> none luks,discard", mapper_name);
        return Ok(());
    }

    let uuid = get_luks_uuid(&luks_device)?;

    // Determine keyfile path
    let keyfile = config
        .disk
        .keyfile_path
        .as_deref()
        .unwrap_or("none");

    let content = format!(
        r#"# /etc/crypttab - Generated by Deploytix
# <name>    <device>              <keyfile>    <options>
{name}    UUID={uuid}    {keyfile}    luks,discard
"#,
        name = mapper_name,
        uuid = uuid,
        keyfile = keyfile,
    );

    let crypttab_path = format!("{}/etc/crypttab", install_root);
    fs::create_dir_all(format!("{}/etc", install_root))?;
    fs::write(&crypttab_path, content)?;

    info!("Crypttab written to {}", crypttab_path);
    Ok(())
}
