//! Crypttab generation for LUKS containers

use crate::config::{DeploymentConfig, SWAP_MAPPER_NAME};
use crate::configure::encryption::{get_luks_uuid, LuksContainer};
use crate::configure::keyfiles::{keyfile_path, VolumeKeyfile};
use crate::disk::detection::partition_path;
use crate::disk::formatting::get_partition_uuid;
use crate::utils::command::CommandRunner;
use crate::utils::error::Result;
use std::fs;
use tracing::info;

/// Options for the random-key swap entry. `swap` is the flag the
/// crypttab-unlock hook keys on to open the device in plain mode and re-run
/// mkswap; the cipher and key size mirror the LUKS2 defaults.
pub const SWAP_CRYPTTAB_OPTIONS: &str = "swap,cipher=aes-xts-plain64,size=256";

/// Build the crypttab options string based on integrity configuration.
/// When integrity is enabled, TRIM/discard is not supported by dm-integrity.
fn crypttab_options(integrity: bool) -> &'static str {
    if integrity {
        "luks"
    } else {
        "luks,discard"
    }
}

/// Public accessor for crypttab options (used by LVM thin crypttab generation).
pub fn crypttab_options_pub(integrity: bool) -> &'static str {
    crypttab_options(integrity)
}

/// Generate /etc/crypttab for the installed system (legacy single-volume)
///
/// If `boot_luks_partition` is Some, an additional entry for the encrypted
/// /boot partition (LUKS1) will be included.
#[allow(dead_code)]
pub fn generate_crypttab(
    cmd: &CommandRunner,
    config: &DeploymentConfig,
    device: &str,
    luks_partition: u32,
    boot_luks_partition: Option<u32>,
    install_root: &str,
) -> Result<()> {
    info!("Generating /etc/crypttab");

    let luks_device = partition_path(device, luks_partition);
    let options = crypttab_options(config.disk.integrity);

    // Extract the mapping name without "Crypt-" prefix for crypttab
    // crypttab uses the base name (e.g., "Root"), the hook adds "Crypt-" prefix
    let mapper_name = config
        .disk
        .luks_mapper_name
        .trim_start_matches("Crypt-")
        .to_string();

    if cmd.is_dry_run() {
        println!("  [dry-run] Would generate /etc/crypttab:");
        println!("    {} UUID=<LUKS_UUID> none {}", mapper_name, options);
        if boot_luks_partition.is_some() {
            let boot_mapper = config
                .disk
                .luks_boot_mapper_name
                .trim_start_matches("Crypt-");
            // Boot partition uses LUKS1, which doesn't support integrity;
            // always use discard for boot
            println!(
                "    {} UUID=<BOOT_LUKS_UUID> none luks,discard",
                boot_mapper
            );
        }
        return Ok(());
    }

    let uuid = get_luks_uuid(&luks_device)?;

    // Determine keyfile path
    let keyfile = config.disk.keyfile_path.as_deref().unwrap_or("none");

    let mut content = format!(
        r#"# /etc/crypttab - Generated by Deploytix
# <name>    <device>              <keyfile>    <options>
{name}    UUID={uuid}    {keyfile}    {options}
"#,
        name = mapper_name,
        uuid = uuid,
        keyfile = keyfile,
        options = options,
    );

    // Add boot LUKS1 entry if boot encryption is enabled
    // Boot always uses discard (LUKS1 doesn't support integrity)
    if let Some(boot_part_num) = boot_luks_partition {
        let boot_device = partition_path(device, boot_part_num);
        let boot_uuid = get_luks_uuid(&boot_device)?;
        let boot_mapper = config
            .disk
            .luks_boot_mapper_name
            .trim_start_matches("Crypt-")
            .to_string();

        content.push_str(&format!(
            "{name}    UUID={uuid}    {keyfile}    luks,discard\n",
            name = boot_mapper,
            uuid = boot_uuid,
            keyfile = keyfile,
        ));
    }

    let crypttab_path = format!("{}/etc/crypttab", install_root);
    fs::create_dir_all(format!("{}/etc", install_root))?;
    fs::write(&crypttab_path, content)?;

    info!("Crypttab written to {}", crypttab_path);
    Ok(())
}

/// Generate /etc/crypttab for multi-volume encrypted system
///
/// Creates entries for ROOT, USR, VAR, HOME and optionally BOOT with keyfile
/// paths for automatic unlocking during initramfs.
///
/// `swap_device`, when set, adds a random-key swap entry: a plain (header-less)
/// dm-crypt device re-keyed from /dev/urandom on every boot by the
/// crypttab-unlock hook, so swapped-out memory is unrecoverable after
/// shutdown. Only passed when hibernation is off — see
/// [`DeploymentConfig::encrypted_swap`].
#[allow(clippy::too_many_arguments)]
pub fn generate_crypttab_multi_volume(
    cmd: &CommandRunner,
    containers: &[LuksContainer],
    boot_container: Option<&LuksContainer>,
    keyfiles: &[VolumeKeyfile],
    integrity: bool,
    swap_device: Option<&str>,
    install_root: &str,
) -> Result<()> {
    let total = containers.len() + if boot_container.is_some() { 1 } else { 0 };
    let options = crypttab_options(integrity);
    info!("Generating /etc/crypttab for {} encrypted volumes", total);

    if cmd.is_dry_run() {
        println!("  [dry-run] Would generate /etc/crypttab:");
        for container in containers {
            let kf_path = keyfile_path(&container.volume_name);
            println!(
                "    {} UUID=<LUKS_UUID> {} {}",
                container.volume_name, kf_path, options
            );
        }
        if let Some(boot) = boot_container {
            let kf_path = keyfile_path(&boot.volume_name);
            // Boot uses LUKS1, always discard (no integrity)
            println!(
                "    {} UUID=<BOOT_LUKS_UUID> {} luks,discard",
                boot.volume_name, kf_path
            );
        }
        if swap_device.is_some() {
            println!(
                "    {} UUID=<SWAP_UUID> /dev/urandom {}",
                SWAP_MAPPER_NAME, SWAP_CRYPTTAB_OPTIONS
            );
        }
        return Ok(());
    }

    let mut content = String::from(
        "# /etc/crypttab - Generated by Deploytix\n\
         # Multi-volume encrypted system with keyfile-based automatic unlocking\n\
         #\n\
         # <name>    <device>              <keyfile>                              <options>\n",
    );

    // Write entries for all data volumes (Root, Usr, Var, Home)
    for container in containers {
        let uuid = get_luks_uuid(&container.device)?;

        // Find matching keyfile
        let kf_path = keyfiles
            .iter()
            .find(|k| k.volume_name == container.volume_name)
            .map(|k| k.keyfile_path.clone())
            .unwrap_or_else(|| keyfile_path(&container.volume_name));

        content.push_str(&format!(
            "{name}    UUID={uuid}    {keyfile}    {options}\n",
            name = container.volume_name,
            uuid = uuid,
            keyfile = kf_path,
            options = options,
        ));
    }

    // Write entry for encrypted /boot (LUKS1) if present
    // Boot always uses discard (LUKS1 doesn't support integrity)
    if let Some(boot) = boot_container {
        let uuid = get_luks_uuid(&boot.device)?;

        let kf_path = keyfiles
            .iter()
            .find(|k| k.volume_name == boot.volume_name)
            .map(|k| k.keyfile_path.clone())
            .unwrap_or_else(|| keyfile_path(&boot.volume_name));

        content.push_str(&format!(
            "{name}    UUID={uuid}    {keyfile}    luks,discard\n",
            name = boot.volume_name,
            uuid = uuid,
            keyfile = kf_path,
        ));
    }

    // Random-key swap. Addressed by UUID of the *raw* partition: the mapper
    // gets a new key (and so a new filesystem UUID) on every boot, so only the
    // partition's own UUID is stable.
    if let Some(swap_dev) = swap_device {
        let uuid = get_partition_uuid(swap_dev)?;
        content.push_str(&format!(
            "{name}    UUID={uuid}    /dev/urandom    {options}\n",
            name = SWAP_MAPPER_NAME,
            uuid = uuid,
            options = SWAP_CRYPTTAB_OPTIONS,
        ));
    }

    let crypttab_path = format!("{}/etc/crypttab", install_root);
    fs::create_dir_all(format!("{}/etc", install_root))?;
    fs::write(&crypttab_path, &content)?;

    info!(
        "Crypttab written to {} with {} entries",
        crypttab_path,
        total + usize::from(swap_device.is_some())
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── crypttab_options ─────────────────────────────────────────────────────

    #[test]
    fn crypttab_options_without_integrity_includes_discard() {
        assert_eq!(crypttab_options(false), "luks,discard");
    }

    #[test]
    fn crypttab_options_with_integrity_omits_discard() {
        // dm-integrity is incompatible with TRIM/discard
        assert_eq!(crypttab_options(true), "luks");
    }

    // ── random-key swap ──────────────────────────────────────────────────────

    #[test]
    fn swap_options_carry_the_flag_the_hook_keys_on() {
        // crypttab-unlock branches on a bare `swap` element to open the device
        // in plain mode; the comma framing is what its `case ",$options,"`
        // match relies on.
        let framed = format!(",{},", SWAP_CRYPTTAB_OPTIONS);
        assert!(
            framed.contains(",swap,"),
            "hook matches on a bare `swap` element, got {}",
            SWAP_CRYPTTAB_OPTIONS
        );
        assert!(SWAP_CRYPTTAB_OPTIONS.contains("cipher=aes-xts-plain64"));
        assert!(SWAP_CRYPTTAB_OPTIONS.contains("size=256"));
        assert!(
            !SWAP_CRYPTTAB_OPTIONS.contains("luks"),
            "random-key swap is plain dm-crypt, it has no LUKS header"
        );
    }

    #[test]
    fn swap_mapper_name_is_shared_with_fstab() {
        // fstab addresses swap as /dev/mapper/<name> because the mapper is
        // re-keyed each boot and has no stable UUID; the two must agree.
        assert_eq!(SWAP_MAPPER_NAME, "Crypt-Swap");
    }
}
